name: loop_log
description: LoopLog app with orders, inventory, local storage, and PDF export.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  pdf: ^3.11.0
  printing: ^5.9.0
  google_fonts: ^6.1.0
  provider: ^6.1.2 # Or latest version


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
